### ISSUE TITLE
build cython version

### ISSUE THREAD

**Issue by KPbICO6Ou** [KPbICO6Ou/lancalc#14]
Hi, I tried to build binary file to cython3 (to reduce the size of the executable file)

```
cython3 --embed -o main.c main.py
gcc -Os -I /usr/include/python3.12 -o main main.c -lpython3.12 -lpthread -lm -lutil -ldl
```
but I get an error when calculating

```
Traceback (most recent call last):
  File "main.py", line 157, in main.LanCalc.calculate_network
TypeError: calculate_network() takes exactly 1 positional argument (2 given)
```

any ideas on how to fix this?

**Comment by apollozen** [comment]
https://github.com/KPbICO6Ou/lancalc/commit/a995aabda6b1e4d7798d94fde3eb0630e0e839b6
has been fixed
