### ISSUE TITLE
long time to calculate class A networks 

### ISSUE THREAD

**Issue by drunk3nme** [KPbICO6Ou/lancalc#16]
![image](https://github.com/KPbICO6Ou/lancalc/assets/172490100/15d074d1-dc5d-42cc-a0b1-b86e2941c18d)
 subj

**Comment by apollozen** [comment]
looks like ipaddress library takes a long time to calculate

**Comment by apollozen** [comment]
@drunk3nme try new main version please

**Comment by drunk3nme** [comment]
All good, Thank you
